// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/course.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Course 课程模型
type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	TypeId        int32                  `protobuf:"varint,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeCode      string                 `protobuf:"bytes,7,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // 0表示未删除，>0表示删除时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Course) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Course) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *Course) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Course) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Course) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Course) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Course) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Course) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// CreateCourseRequest 创建课程请求
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TypeId        int32                  `protobuf:"varint,5,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeCode      string                 `protobuf:"bytes,6,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_proto_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCourseRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *CreateCourseRequest) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *CreateCourseRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateCourseRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *CreateCourseRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// CreateCourseResponse 创建课程响应
type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_proto_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *CreateCourseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetCourseRequest 获取课程请求
type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_proto_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetCourseResponse 获取课程响应
type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_proto_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *GetCourseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetAllCoursesRequest 获取所有课程请求
type GetAllCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCoursesRequest) Reset() {
	*x = GetAllCoursesRequest{}
	mi := &file_proto_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoursesRequest) ProtoMessage() {}

func (x *GetAllCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetAllCoursesRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{5}
}

// GetAllCoursesResponse 获取所有课程响应
type GetAllCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCoursesResponse) Reset() {
	*x = GetAllCoursesResponse{}
	mi := &file_proto_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoursesResponse) ProtoMessage() {}

func (x *GetAllCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetAllCoursesResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *GetAllCoursesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateCourseRequest 更新课程请求
type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	TypeId        int32                  `protobuf:"varint,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeCode      string                 `protobuf:"bytes,7,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_proto_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCourseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateCourseRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *UpdateCourseRequest) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *UpdateCourseRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateCourseRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// UpdateCourseResponse 更新课程响应
type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_proto_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *UpdateCourseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeleteCourseRequest 删除课程请求
type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_proto_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteCourseResponse 删除课程响应
type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_proto_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCourseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_course_proto protoreflect.FileDescriptor

const file_proto_course_proto_rawDesc = "" +
	"\n" +
	"\x12proto/course.proto\x12\x06course\"\xe9\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\x05R\x06typeId\x12\x1b\n" +
	"\ttype_code\x18\a \x01(\tR\btypeCode\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\r \x01(\x03R\tdeletedAt\"\x89\x02\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x17\n" +
	"\atype_id\x18\x05 \x01(\x05R\x06typeId\x12\x1b\n" +
	"\ttype_code\x18\x06 \x01(\tR\btypeCode\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"T\n" +
	"\x14CreateCourseResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\x11GetCourseResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14GetAllCoursesRequest\"W\n" +
	"\x15GetAllCoursesResponse\x12(\n" +
	"\acourses\x18\x01 \x03(\v2\x0e.course.CourseR\acourses\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xfa\x01\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x17\n" +
	"\atype_id\x18\x06 \x01(\x05R\x06typeId\x12\x1b\n" +
	"\ttype_code\x18\a \x01(\tR\btypeCode\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"T\n" +
	"\x14UpdateCourseResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x80\x03\n" +
	"\rCourseService\x12I\n" +
	"\fCreateCourse\x12\x1b.course.CreateCourseRequest\x1a\x1c.course.CreateCourseResponse\x12@\n" +
	"\tGetCourse\x12\x18.course.GetCourseRequest\x1a\x19.course.GetCourseResponse\x12L\n" +
	"\rGetAllCourses\x12\x1c.course.GetAllCoursesRequest\x1a\x1d.course.GetAllCoursesResponse\x12I\n" +
	"\fUpdateCourse\x12\x1b.course.UpdateCourseRequest\x1a\x1c.course.UpdateCourseResponse\x12I\n" +
	"\fDeleteCourse\x12\x1b.course.DeleteCourseRequest\x1a\x1c.course.DeleteCourseResponseB+Z)github.com/haoyunfeng/edu-course-proto/pbb\x06proto3"

var (
	file_proto_course_proto_rawDescOnce sync.Once
	file_proto_course_proto_rawDescData []byte
)

func file_proto_course_proto_rawDescGZIP() []byte {
	file_proto_course_proto_rawDescOnce.Do(func() {
		file_proto_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_course_proto_rawDesc), len(file_proto_course_proto_rawDesc)))
	})
	return file_proto_course_proto_rawDescData
}

var file_proto_course_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_course_proto_goTypes = []any{
	(*Course)(nil),                // 0: course.Course
	(*CreateCourseRequest)(nil),   // 1: course.CreateCourseRequest
	(*CreateCourseResponse)(nil),  // 2: course.CreateCourseResponse
	(*GetCourseRequest)(nil),      // 3: course.GetCourseRequest
	(*GetCourseResponse)(nil),     // 4: course.GetCourseResponse
	(*GetAllCoursesRequest)(nil),  // 5: course.GetAllCoursesRequest
	(*GetAllCoursesResponse)(nil), // 6: course.GetAllCoursesResponse
	(*UpdateCourseRequest)(nil),   // 7: course.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),  // 8: course.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),   // 9: course.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),  // 10: course.DeleteCourseResponse
}
var file_proto_course_proto_depIdxs = []int32{
	0,  // 0: course.CreateCourseResponse.course:type_name -> course.Course
	0,  // 1: course.GetCourseResponse.course:type_name -> course.Course
	0,  // 2: course.GetAllCoursesResponse.courses:type_name -> course.Course
	0,  // 3: course.UpdateCourseResponse.course:type_name -> course.Course
	1,  // 4: course.CourseService.CreateCourse:input_type -> course.CreateCourseRequest
	3,  // 5: course.CourseService.GetCourse:input_type -> course.GetCourseRequest
	5,  // 6: course.CourseService.GetAllCourses:input_type -> course.GetAllCoursesRequest
	7,  // 7: course.CourseService.UpdateCourse:input_type -> course.UpdateCourseRequest
	9,  // 8: course.CourseService.DeleteCourse:input_type -> course.DeleteCourseRequest
	2,  // 9: course.CourseService.CreateCourse:output_type -> course.CreateCourseResponse
	4,  // 10: course.CourseService.GetCourse:output_type -> course.GetCourseResponse
	6,  // 11: course.CourseService.GetAllCourses:output_type -> course.GetAllCoursesResponse
	8,  // 12: course.CourseService.UpdateCourse:output_type -> course.UpdateCourseResponse
	10, // 13: course.CourseService.DeleteCourse:output_type -> course.DeleteCourseResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_course_proto_init() }
func file_proto_course_proto_init() {
	if File_proto_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_course_proto_rawDesc), len(file_proto_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_course_proto_goTypes,
		DependencyIndexes: file_proto_course_proto_depIdxs,
		MessageInfos:      file_proto_course_proto_msgTypes,
	}.Build()
	File_proto_course_proto = out.File
	file_proto_course_proto_goTypes = nil
	file_proto_course_proto_depIdxs = nil
}
